#include "ProtoDisableWarning.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: field_behavior.proto

#include "field_behavior.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace google {
namespace api {
}  // namespace api
}  // namespace google
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_field_5fbehavior_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_field_5fbehavior_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_field_5fbehavior_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_field_5fbehavior_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_field_5fbehavior_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024field_behavior.proto\022\ngoogle.api\032 goog"
  "le/protobuf/descriptor.proto*\217\001\n\rFieldBe"
  "havior\022\036\n\032FIELD_BEHAVIOR_UNSPECIFIED\020\000\022\014"
  "\n\010OPTIONAL\020\001\022\014\n\010REQUIRED\020\002\022\017\n\013OUTPUT_ONL"
  "Y\020\003\022\016\n\nINPUT_ONLY\020\004\022\r\n\tIMMUTABLE\020\005\022\022\n\016UN"
  "ORDERED_LIST\020\006:Q\n\016field_behavior\022\035.googl"
  "e.protobuf.FieldOptions\030\234\010 \003(\0162\031.google."
  "api.FieldBehaviorBp\n\016com.google.apiB\022Fie"
  "ldBehaviorProtoP\001ZAgoogle.golang.org/gen"
  "proto/googleapis/api/annotations;annotat"
  "ions\242\002\004GAPIb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_field_5fbehavior_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_field_5fbehavior_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_field_5fbehavior_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_field_5fbehavior_2eproto = {
  false, false, descriptor_table_protodef_field_5fbehavior_2eproto, "field_behavior.proto", 419,
  &descriptor_table_field_5fbehavior_2eproto_once, descriptor_table_field_5fbehavior_2eproto_sccs, descriptor_table_field_5fbehavior_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_field_5fbehavior_2eproto::offsets,
  file_level_metadata_field_5fbehavior_2eproto, 0, file_level_enum_descriptors_field_5fbehavior_2eproto, file_level_service_descriptors_field_5fbehavior_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_field_5fbehavior_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_field_5fbehavior_2eproto)), true);
namespace google {
namespace api {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FieldBehavior_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_field_5fbehavior_2eproto);
  return file_level_enum_descriptors_field_5fbehavior_2eproto[0];
}
bool FieldBehavior_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedEnumTypeTraits< ::google::api::FieldBehavior, ::google::api::FieldBehavior_IsValid>, 14, true >
  field_behavior(kFieldBehaviorFieldNumber, static_cast< ::google::api::FieldBehavior >(0));

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace google
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
