#include "ProtoDisableWarning.h"
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nvidia/a2x-interface-proto/nvidia.ace.services.a2x.v1.proto

#include "nvidia/a2x-interface-proto/nvidia.ace.services.a2x.v1.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace nvidia {
namespace ace {
namespace services {
namespace a2x {
namespace v1 {
}  // namespace v1
}  // namespace a2x
}  // namespace services
}  // namespace ace
}  // namespace nvidia
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n;nvidia/a2x-interface-proto/nvidia.ace."
  "services.a2x.v1.proto\022\032nvidia.ace.servic"
  "es.a2x.v1\0322nvidia/a2x-interface-proto/nv"
  "idia.ace.a2x.v1.proto\032Bnvidia/animation-"
  "common-interface-proto/nvidia.ace.status"
  ".v1.proto2a\n\nA2XService\022S\n\017PushAudioStre"
  "am\022\036.nvidia.ace.a2x.v1.AudioStream\032\034.nvi"
  "dia.ace.status.v1.Status\"\000(\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_deps[2] = {
  &::descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2ea2x_2ev1_2eproto,
  &::descriptor_table_nvidia_2fanimation_2dcommon_2dinterface_2dproto_2fnvidia_2eace_2estatus_2ev1_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto = {
  false, false, descriptor_table_protodef_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto, "nvidia/a2x-interface-proto/nvidia.ace.services.a2x.v1.proto", 316,
  &descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_once, descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_sccs, descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto_deps, 0, 2,
  schemas, file_default_instances, TableStruct_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto::offsets,
  file_level_metadata_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto, 0, file_level_enum_descriptors_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto, file_level_service_descriptors_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_nvidia_2fa2x_2dinterface_2dproto_2fnvidia_2eace_2eservices_2ea2x_2ev1_2eproto)), true);
namespace nvidia {
namespace ace {
namespace services {
namespace a2x {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace a2x
}  // namespace services
}  // namespace ace
}  // namespace nvidia
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
