// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ai/inworld/studio/v1alpha/player_profiles.proto
#ifndef GRPC_player_5fprofiles_2eproto__INCLUDED
#define GRPC_player_5fprofiles_2eproto__INCLUDED

#include "ai/inworld/studio/v1alpha/player_profiles.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ai {
namespace inworld {
namespace studio {
namespace v1alpha {

// Service to manage PlayerProfiles.
class PlayerProfileService final {
 public:
  static constexpr char const* service_full_name() {
    return "ai.inworld.studio.v1alpha.PlayerProfileService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Update an existing PlayerProfile.
    virtual ::grpc::Status UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>> AsyncUpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>>(AsyncUpdatePlayerProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>> PrepareAsyncUpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>>(PrepareAsyncUpdatePlayerProfileRaw(context, request, cq));
    }
    // List the PlayerProfile of a workspace.
    virtual ::grpc::Status GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>> AsyncGetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>>(AsyncGetPlayerProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>> PrepareAsyncGetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>>(PrepareAsyncGetPlayerProfileRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Update an existing PlayerProfile.
      virtual void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // List the PlayerProfile of a workspace.
      virtual void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>* AsyncUpdatePlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>* PrepareAsyncUpdatePlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>* AsyncGetPlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ai::inworld::studio::v1alpha::PlayerProfile>* PrepareAsyncGetPlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>> AsyncUpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>>(AsyncUpdatePlayerProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>> PrepareAsyncUpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>>(PrepareAsyncUpdatePlayerProfileRaw(context, request, cq));
    }
    ::grpc::Status GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>> AsyncGetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>>(AsyncGetPlayerProfileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>> PrepareAsyncGetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>>(PrepareAsyncGetPlayerProfileRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void UpdatePlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetPlayerProfile(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>* AsyncUpdatePlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>* PrepareAsyncUpdatePlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>* AsyncGetPlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ai::inworld::studio::v1alpha::PlayerProfile>* PrepareAsyncGetPlayerProfileRaw(::grpc::ClientContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdatePlayerProfile_;
    const ::grpc::internal::RpcMethod rpcmethod_GetPlayerProfile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Update an existing PlayerProfile.
    virtual ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response);
    // List the PlayerProfile of a workspace.
    virtual ::grpc::Status GetPlayerProfile(::grpc::ServerContext* context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdatePlayerProfile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdatePlayerProfile(::grpc::ServerContext* context, ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::grpc::ServerAsyncResponseWriter< ::ai::inworld::studio::v1alpha::PlayerProfile>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetPlayerProfile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlayerProfile(::grpc::ServerContext* context, ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::grpc::ServerAsyncResponseWriter< ::ai::inworld::studio::v1alpha::PlayerProfile>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdatePlayerProfile<WithAsyncMethod_GetPlayerProfile<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_UpdatePlayerProfile() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) { return this->UpdatePlayerProfile(context, request, response); }));}
    void SetMessageAllocatorFor_UpdatePlayerProfile(
        ::grpc::experimental::MessageAllocator< ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdatePlayerProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdatePlayerProfile(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetPlayerProfile() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* request, ::ai::inworld::studio::v1alpha::PlayerProfile* response) { return this->GetPlayerProfile(context, request, response); }));}
    void SetMessageAllocatorFor_GetPlayerProfile(
        ::grpc::experimental::MessageAllocator< ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetPlayerProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetPlayerProfile(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_UpdatePlayerProfile<ExperimentalWithCallbackMethod_GetPlayerProfile<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_UpdatePlayerProfile<ExperimentalWithCallbackMethod_GetPlayerProfile<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdatePlayerProfile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetPlayerProfile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdatePlayerProfile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdatePlayerProfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetPlayerProfile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPlayerProfile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_UpdatePlayerProfile() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdatePlayerProfile(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* UpdatePlayerProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* UpdatePlayerProfile(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetPlayerProfile() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetPlayerProfile(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetPlayerProfile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetPlayerProfile(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdatePlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdatePlayerProfile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>* streamer) {
                       return this->StreamedUpdatePlayerProfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdatePlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdatePlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdatePlayerProfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ai::inworld::studio::v1alpha::UpdatePlayerProfileRequest,::ai::inworld::studio::v1alpha::PlayerProfile>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPlayerProfile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetPlayerProfile() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest, ::ai::inworld::studio::v1alpha::PlayerProfile>* streamer) {
                       return this->StreamedGetPlayerProfile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetPlayerProfile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPlayerProfile(::grpc::ServerContext* /*context*/, const ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest* /*request*/, ::ai::inworld::studio::v1alpha::PlayerProfile* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPlayerProfile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ai::inworld::studio::v1alpha::GetPlayerProfileRequest,::ai::inworld::studio::v1alpha::PlayerProfile>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdatePlayerProfile<WithStreamedUnaryMethod_GetPlayerProfile<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdatePlayerProfile<WithStreamedUnaryMethod_GetPlayerProfile<Service > > StreamedService;
};

}  // namespace v1alpha
}  // namespace studio
}  // namespace inworld
}  // namespace ai


#endif  // GRPC_player_5fprofiles_2eproto__INCLUDED
