// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvidia/animation-controller-interface-main-proto/proto/nvidia_ace.services.animation_controller.v1.proto
#ifndef GRPC_nvidia_2fanimation_2dcontroller_2dinterface_2dmain_2dproto_2fproto_2fnvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED
#define GRPC_nvidia_2fanimation_2dcontroller_2dinterface_2dmain_2dproto_2fproto_2fnvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED

#include "nvidia/animation-controller-interface-main-proto/proto/nvidia_ace.services.animation_controller.v1.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace nvidia_ace {
namespace services {
namespace animation_controller {
namespace v1 {

class AnimationControllerService final {
 public:
  static constexpr char const* service_full_name() {
    return "nvidia_ace.services.animation_controller.v1.AnimationControllerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // First request an ID to communicate with the service
    virtual ::grpc::Status RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>> AsyncRequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>>(AsyncRequestAnimationIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>> PrepareAsyncRequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>>(PrepareAsyncRequestAnimationIdsRaw(context, request, cq));
    }
    // Then start pulling animation data
    std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PullAnimationDataStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPullAnimationDataStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPullAnimationDataStreamRaw(context, request, cq));
    }
    // Send audio data as needed
    std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>> PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>>(PushAudioStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>> AsyncPushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>>(AsyncPushAudioStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>> PrepareAsyncPushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>>(PrepareAsyncPushAudioStreamRaw(context, response, cq));
    }
    // Update animation graph variables as needed
    std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(UpdateAnimationGraphVariableRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> AsyncUpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(AsyncUpdateAnimationGraphVariableRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> PrepareAsyncUpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(PrepareAsyncUpdateAnimationGraphVariableRaw(context, response, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // First request an ID to communicate with the service
      virtual void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Then start pulling animation data
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PullAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) = 0;
      #else
      virtual void PullAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::experimental::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) = 0;
      #endif
      // Send audio data as needed
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::a2x::v1::AudioStream>* reactor) = 0;
      #else
      virtual void PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::experimental::ClientWriteReactor< ::nvidia_ace::a2x::v1::AudioStream>* reactor) = 0;
      #endif
      // Update animation graph variables as needed
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reactor) = 0;
      #else
      virtual void UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::experimental::ClientWriteReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* AsyncRequestAnimationIdsRaw(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* PrepareAsyncRequestAnimationIdsRaw(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>* PushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>* AsyncPushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::a2x::v1::AudioStream>* PrepareAsyncPushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* UpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* AsyncUpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* PrepareAsyncUpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>> AsyncRequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>>(AsyncRequestAnimationIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>> PrepareAsyncRequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>>(PrepareAsyncRequestAnimationIdsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PullAnimationDataStreamRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> AsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(AsyncPullAnimationDataStreamRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>> PrepareAsyncPullAnimationDataStream(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>>(PrepareAsyncPullAnimationDataStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::a2x::v1::AudioStream>> PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::a2x::v1::AudioStream>>(PushAudioStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>> AsyncPushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>>(AsyncPushAudioStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>> PrepareAsyncPushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>>(PrepareAsyncPushAudioStreamRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(UpdateAnimationGraphVariableRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> AsyncUpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(AsyncUpdateAnimationGraphVariableRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>> PrepareAsyncUpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>>(PrepareAsyncUpdateAnimationGraphVariableRaw(context, response, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RequestAnimationIds(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PullAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) override;
      #else
      void PullAnimationDataStream(::grpc::ClientContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::experimental::ClientReadReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::a2x::v1::AudioStream>* reactor) override;
      #else
      void PushAudioStream(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::experimental::ClientWriteReactor< ::nvidia_ace::a2x::v1::AudioStream>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::ClientWriteReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reactor) override;
      #else
      void UpdateAnimationGraphVariable(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::experimental::ClientWriteReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* AsyncRequestAnimationIdsRaw(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* PrepareAsyncRequestAnimationIdsRaw(::grpc::ClientContext* context, const ::google::protobuf_inworld::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* AsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PrepareAsyncPullAnimationDataStreamRaw(::grpc::ClientContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::nvidia_ace::a2x::v1::AudioStream>* PushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>* AsyncPushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::a2x::v1::AudioStream>* PrepareAsyncPushAudioStreamRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* UpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* AsyncUpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* PrepareAsyncUpdateAnimationGraphVariableRaw(::grpc::ClientContext* context, ::nvidia_ace::status::v1::Status* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestAnimationIds_;
    const ::grpc::internal::RpcMethod rpcmethod_PullAnimationDataStream_;
    const ::grpc::internal::RpcMethod rpcmethod_PushAudioStream_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateAnimationGraphVariable_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // First request an ID to communicate with the service
    virtual ::grpc::Status RequestAnimationIds(::grpc::ServerContext* context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response);
    // Then start pulling animation data
    virtual ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* context, const ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* writer);
    // Send audio data as needed
    virtual ::grpc::Status PushAudioStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* reader, ::nvidia_ace::status::v1::Status* response);
    // Update animation graph variables as needed
    virtual ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* context, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reader, ::nvidia_ace::status::v1::Status* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestAnimationIds() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestAnimationIds(::grpc::ServerContext* context, ::google::protobuf_inworld::Empty* request, ::grpc::ServerAsyncResponseWriter< ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullAnimationDataStream(::grpc::ServerContext* context, ::nvidia_ace::animation_id::v1::AnimationIds* request, ::grpc::ServerAsyncWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PushAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PushAudioStream() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_PushAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushAudioStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::nvidia_ace::status::v1::Status, ::nvidia_ace::a2x::v1::AudioStream>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateAnimationGraphVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateAnimationGraphVariable() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateAnimationGraphVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateAnimationGraphVariable(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::nvidia_ace::status::v1::Status, ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestAnimationIds<WithAsyncMethod_PullAnimationDataStream<WithAsyncMethod_PushAudioStream<WithAsyncMethod_UpdateAnimationGraphVariable<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RequestAnimationIds() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf_inworld::Empty, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::google::protobuf_inworld::Empty* request, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* response) { return this->RequestAnimationIds(context, request, response); }));}
    void SetMessageAllocatorFor_RequestAnimationIds(
        ::grpc::experimental::MessageAllocator< ::google::protobuf_inworld::Empty, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf_inworld::Empty, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RequestAnimationIds(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RequestAnimationIds(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PullAnimationDataStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::nvidia_ace::animation_id::v1::AnimationIds* request) { return this->PullAnimationDataStream(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::nvidia_ace::animation_data::v1::AnimationDataStream>* PullAnimationDataStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_PushAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_PushAudioStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::nvidia_ace::a2x::v1::AudioStream, ::nvidia_ace::status::v1::Status>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::nvidia_ace::status::v1::Status* response) { return this->PushAudioStream(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_PushAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::nvidia_ace::a2x::v1::AudioStream>* PushAudioStream(
      ::grpc::CallbackServerContext* /*context*/, ::nvidia_ace::status::v1::Status* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::nvidia_ace::a2x::v1::AudioStream>* PushAudioStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::nvidia_ace::status::v1::Status* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_UpdateAnimationGraphVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_UpdateAnimationGraphVariable() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest, ::nvidia_ace::status::v1::Status>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::nvidia_ace::status::v1::Status* response) { return this->UpdateAnimationGraphVariable(context, response); }));
    }
    ~ExperimentalWithCallbackMethod_UpdateAnimationGraphVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* UpdateAnimationGraphVariable(
      ::grpc::CallbackServerContext* /*context*/, ::nvidia_ace::status::v1::Status* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* UpdateAnimationGraphVariable(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::nvidia_ace::status::v1::Status* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RequestAnimationIds<ExperimentalWithCallbackMethod_PullAnimationDataStream<ExperimentalWithCallbackMethod_PushAudioStream<ExperimentalWithCallbackMethod_UpdateAnimationGraphVariable<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RequestAnimationIds<ExperimentalWithCallbackMethod_PullAnimationDataStream<ExperimentalWithCallbackMethod_PushAudioStream<ExperimentalWithCallbackMethod_UpdateAnimationGraphVariable<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestAnimationIds() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PushAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PushAudioStream() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_PushAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateAnimationGraphVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateAnimationGraphVariable() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateAnimationGraphVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestAnimationIds() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestAnimationIds(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullAnimationDataStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PushAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PushAudioStream() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_PushAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPushAudioStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateAnimationGraphVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateAnimationGraphVariable() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateAnimationGraphVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateAnimationGraphVariable(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(3, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RequestAnimationIds() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestAnimationIds(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RequestAnimationIds(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RequestAnimationIds(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PullAnimationDataStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->PullAnimationDataStream(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* PullAnimationDataStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* PullAnimationDataStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_PushAudioStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_PushAudioStream() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->PushAudioStream(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_PushAudioStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PushAudioStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::a2x::v1::AudioStream>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* PushAudioStream(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* PushAudioStream(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_UpdateAnimationGraphVariable : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_UpdateAnimationGraphVariable() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, ::grpc::ByteBuffer* response) { return this->UpdateAnimationGraphVariable(context, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_UpdateAnimationGraphVariable() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateAnimationGraphVariable(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::nvidia_ace::services::animation_controller::v1::AnimationGraphRequest>* /*reader*/, ::nvidia_ace::status::v1::Status* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* UpdateAnimationGraphVariable(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer>* UpdateAnimationGraphVariable(
      ::grpc::experimental::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestAnimationIds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestAnimationIds() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf_inworld::Empty, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf_inworld::Empty, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* streamer) {
                       return this->StreamedRequestAnimationIds(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestAnimationIds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestAnimationIds(::grpc::ServerContext* /*context*/, const ::google::protobuf_inworld::Empty* /*request*/, ::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestAnimationIds(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf_inworld::Empty,::nvidia_ace::services::animation_controller::v1::AnimationIdsOrStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestAnimationIds<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_PullAnimationDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_PullAnimationDataStream() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::nvidia_ace::animation_id::v1::AnimationIds, ::nvidia_ace::animation_data::v1::AnimationDataStream>* streamer) {
                       return this->StreamedPullAnimationDataStream(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_PullAnimationDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PullAnimationDataStream(::grpc::ServerContext* /*context*/, const ::nvidia_ace::animation_id::v1::AnimationIds* /*request*/, ::grpc::ServerWriter< ::nvidia_ace::animation_data::v1::AnimationDataStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedPullAnimationDataStream(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::nvidia_ace::animation_id::v1::AnimationIds,::nvidia_ace::animation_data::v1::AnimationDataStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_PullAnimationDataStream<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestAnimationIds<WithSplitStreamingMethod_PullAnimationDataStream<Service > > StreamedService;
};

}  // namespace v1
}  // namespace animation_controller
}  // namespace services
}  // namespace nvidia_ace


#endif  // GRPC_nvidia_2fanimation_2dcontroller_2dinterface_2dmain_2dproto_2fproto_2fnvidia_5face_2eservices_2eanimation_5fcontroller_2ev1_2eproto__INCLUDED
