# /*************************************************************************************************
# * Copyright 2023-2024 Theai, Inc. dba Inworld AI
# *
# * Use of this source code is governed by the Inworld.ai Software Development Kit License Agreement
# * that can be found in the LICENSE.md file or at https://www.inworld.ai/sdk-license
# *************************************************************************************************/

name: build-mac

on:
  workflow_call:

jobs:
  build-mac:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: git-update-dependecies
      run: git submodule update --init --recursive
    - name: gen
      shell: bash
      run: |
          sh mac-gen.sh > GenLog.txt -Wait -NoNewWindow -PassThru 
          cat GenLog.txt
          if grep -Fxq "$GenLog.txt" "Configuring incomplete"
          then
              exit 1
          fi
          exit 0
    - name: build-mac
      shell: bash
      run: |
          sh mac-build.sh > BuildLog.txt -Wait -NoNewWindow -PassThru
          cat BuildLog.txt
          if (grep -Fxq "$BuildLog.txt" "** BUILD FAILED **")
          then
            exit 1
          fi
          if (grep -Fxq "$BuildLog.txt" "[  FAILED  ]")
          then
            exit 1
          fi
          exit 0
    - uses: actions/cache/save@v3
      with:
        path: build/Package
        key: ndk-cache-mac-${{ github.sha }}

         
